[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = 100.48.17.9

[v3_req]
subjectAltName = @alt_names

[alt_names]
IP.1 = 100.48.17.9
IP.2 = 3.239.122.40
IP.3 = 54.82.46.236
