services:

  app:
    container_name: app
    image: tiagogferreirainfnet/task-pad:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
    env_file:
      - ./.env.development
    restart: unless-stopped
    networks:
      - task-network

  postgres:
    image: postgres:17.1
    container_name: postgres
    restart: always
    shm_size: 100mb
    ports:
      - "5432:5432"
    env_file:
      - ./.env.development
    networks:
      - task-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  #prometheus:
  #  container_name: prometheus
  #  image: prom/prometheus:v3
  #  depends_on:
  #    - app
  #  ports:
  #    - "9090:9090"
  #  volumes:
  #    - ./src/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #  networks:
  #    - task-network

  #grafana:
  #  container_name: grafana
  #  image: grafana/grafana:12.4.2
  #  depends_on:
  #    - prometheus
  #  ports:
  #    - "3000:3000"
  #  environment:
  #    GF_SECURITY_ADMIN_USER: task-pad-grafana
  #    GF_SECURITY_ADMIN_PASSWORD: 8Mb26UH4snzgfLN
  #  networks:
  #    - task-network

networks:
  task-network:
    driver: bridge
