services:

  app:
    image: tiagogferreirainfnet/task-pad:latest
    depends_on:
      - postgres
    container_name: task-pad-app
    ports:
      - "4200:4200"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - task-network

  postgres:
    image: postgres:17.1
    container_name: postgres
    restart: always
    shm_size: 100mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task-pad-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - task-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]

networks:
  task-network:
    driver: bridge
