apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskpad-app
  namespace: app
  labels:
    app: taskpad-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskpad-app
  template:
    metadata:
      labels:
        app: taskpad-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: taskpad-app
          image: tiagogferreirainfnet/task-pad@sha256:726868974273b36edc325292c304c61da89cbc9918271661073fef226468955e
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          startupProbe:
            httpGet:
              path: /live
              port: 4000
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /live
              port: 4000
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 4000
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: PORT
            - name: FIREBASE_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: FIREBASE_SERVICE_ACCOUNT
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_URL

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: taskpad-app-hpa
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskpad-app
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 85
