apiVersion: v1
kind: Service
metadata:
  name: taskpad-app-service
  namespace: app
  labels:
    app: taskpad-app
spec:
  type: NodePort
  selector:
    app: taskpad-app
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080
