apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
stringData:
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USERNAME: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_URL: "${POSTGRES_URL}"
  GRAFANA_USERNAME: "${GRAFANA_SECURITY_ADMIN_USER}"
  GRAFANA_PASSWORD: "${GRAFANA_SECURITY_ADMIN_PASSWORD}"
