apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
stringData:
  username: "${GRAFANA_SECURITY_ADMIN_USER}"
  password: "${GRAFANA_SECURITY_ADMIN_PASSWORD}"
