admin:
  existingSecret: "grafana-secret"
  userKey: username
  passwordKey: password

persistence:
  type: pvc
  enabled: true
  storageClassName: "gp3"
  accessModes:
    - ReadWriteOnce
  size: 2Gi

deploymentStrategy:
  type: Recreate

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://taskpad-prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true
        editable: false

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

service:
  type: NodePort
  nodePort: 32000
