name: Build and Deploy

on:
  push:
    branches: ['disable-ci']
    paths-ignore:
      - 'k8s/**'
      - '.angular/**'
      - '.editorconfig'
      - '.prettierrc'
      - '.gitignore'
      - '.env.template'
      - '.github/**'
      - 'dist/**'
      - 'docker/**'
      - 'tasks.json'
      - 'proxy.conf.js'
      - 'Makefile'
      - 'README.md'
      - 'k6/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/task-pad

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '24.14.0'
      ENVIRONMENT: 'production'

    permissions:
      id-token: write
      contents: read
      packages: read

    outputs:
      image-digest: ${{ steps.build-push.outputs.digest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli@21.2.6

      - name: Create environment files
        run: |
          mkdir -p src/environments
          cp src/environments/environment.template.ts src/environments/environment.ts

          cat > src/environments/environment.production.ts << EOF
          export const environment = {
            production: true,
            firebase: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}'
            }
          };
          EOF

          test -f src/environments/environment.ts || exit 1
          test -f src/environments/environment.production.ts || exit 1

      - name: Cache Angular build cache
        uses: actions/cache@v5
        with:
          path: .angular/cache
          key: ng-build-cache-${{ runner.os }}-${{ hashFiles('src/**/*.ts', 'src/**/*.js', 'angular.json') }}
          restore-keys: |
            ng-build-cache-${{ runner.os }}-

      - name: Build application
        run: ng build --configuration=${{ env.ENVIRONMENT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get version
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.DOCKER_HUB_REPO }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.package-version.outputs.version }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=${{ env.ENVIRONMENT }}
            BUILD_MODE=${{ env.ENVIRONMENT }}

      - name: Dive analyze
        uses: MaxymVlasov/dive-action@v1.6.0
        with:
          image: "${{ env.DOCKER_HUB_REPO }}@${{ steps.build-push.outputs.digest }}"
          config-file: "${{ github.workspace }}/docker/analyze/.dive.yaml"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.0
        with:
          cosign-release: 'v3.0.3'

      - name: Decode Cosign signing key
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          chmod 600 cosign.key

      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-push.outputs.digest  }}
        run: |
          readarray -t tag_array <<< "${TAGS}"
          images=""
          for tag in "${tag_array[@]}"; do
            [[ -n "$tag" ]] && images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key cosign.key ${images}

      - name: Cleanup signing key
        if: always()
        run: |
          rm -f src/environments/environment.production.ts
          rm -f cosign.key

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      NEW_IMAGE_DIGEST: ${{ needs.build.outputs.image-digest }}

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Generate token do App
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ steps.app-token.outputs.token }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::733544352970:role/github-actions-eks-role
          aws-region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name taskpad-cluster

      - name: Extract the current image
        run: |
          CURRENT_IMAGE=$(kubectl get deployment taskpad-app -n app -o jsonpath='{.spec.template.spec.containers[0].image}')
          OLD_IMAGE_DIGEST="${CURRENT_IMAGE##*@}"
          echo "OLD_IMAGE_DIGEST=${OLD_IMAGE_DIGEST}" >> $GITHUB_ENV

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.0
        with:
          cosign-release: 'v3.0.3'

      - name: Decode Cosign signing key
        run: |
          echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub
          chmod 600 cosign.pub

      - name: Verify Docker image signature
        run: cosign verify --key cosign.pub "$DOCKER_HUB_REPO@$NEW_IMAGE_DIGEST"

      - name: Deploy on EKS
        run: |
          kubectl set image deployment/taskpad-app taskpad-app="$DOCKER_HUB_REPO@$NEW_IMAGE_DIGEST" -n app
          kubectl rollout status deployment/taskpad-app -n app --timeout=5m

      - name: Update image in deployment
        run: |
          FILE="k8s/namespace/app/deployment.yaml"
          sed -i "s|$OLD_IMAGE_DIGEST|$NEW_IMAGE_DIGEST|g" "$FILE"
          git config user.name "app-auto-commit-bot[bot]"
          git config user.email "app-auto-commit-bot@github.com"
          git add "$FILE"
          git commit -m "chore: update image to $NEW_IMAGE_DIGEST"
          git push

      - name: Cleanup signing key
        if: always()
        run: rm -f cosign.pub
